### ISSUE TITLE
last checklist before 0.2.0

### ISSUE THREAD

**Issue by Luceos** [flagrow/flarum-ext-image-upload#23]
- [x] update branch alias
- [x] update changelog.md
- [x] update readme and [thread](https://discuss.flarum.org/d/1836-flagrow-image-uploader-for-flarum-forum-messages) about functionality
- [x] merge PR's, like https://github.com/flagrow/flarum-ext-image-upload/pull/25
